// helpers.js — shared utilities
const crypto = require("crypto");

function ok(data, message = "Success", extra = {}) {
  return { success: true, message, data, ...extra };
}
function created(data, message = "Created") {
  return { success: true, message, data };
}
function fail(message, errors) {
  return { success: false, message, ...(errors ? { errors } : {}) };
}
function paged(data, message, page, per_page, total_items) {
  return {
    success: true, message, data,
    pagination: { page, per_page, total_items, total_pages: Math.ceil(total_items / per_page) },
  };
}

function formatTask(row) {
  if (!row) return null;
  return {
    id: row.id, clientId: row.client_id, assignedBy: row.assigned_by ?? null,
    title: row.title, description: row.description ?? null,
    status: row.status, adminStatus: row.admin_status,
    taskType: row.task_type ?? null,
    metadata: safeJson(row.metadata, {}),
    completionNote: row.completion_note ?? null,
    completedAt: row.completed_at ?? null,
    createdAt: row.created_at, updatedAt: row.updated_at,
  };
}

function formatEmployee(row) {
  if (!row) return null;
  return {
    id: row.id, name: row.name, email: row.email ?? null,
    firstName: row.first_name ?? null, lastName: row.last_name ?? null,
    middleName: row.middle_name ?? null, dateOfBirth: row.date_of_birth ?? null,
    gender: row.gender ?? null, phone: row.phone ?? null, sin: row.sin ?? null,
    addressLine1: row.address_line_1 ?? null, addressLine2: row.address_line_2 ?? null,
    city: row.city ?? null, country: row.country ?? null,
    provinceState: row.province_state ?? null, postalCode: row.postal_code ?? null,
    startDate: row.start_date ?? null, position: row.position ?? null,
    department: row.department ?? null,
    hourlyRate: row.hourly_rate ?? null, federalTaxCredit: row.federal_tax_credit ?? null,
    provincialTaxCredit: row.provincial_tax_credit ?? null, salary: row.salary ?? null,
    metadata: safeJson(row.metadata, {}),
    createdAt: row.created_at, updatedAt: row.updated_at,
  };
}

function formatEntry(row) {
  if (!row) return null;
  return {
    id: row.id, periodLabel: row.period_label,
    periodStart: row.period_start, periodEnd: row.period_end,
    status: row.status,
    employeeIds: safeJson(row.employee_ids, []),
    totalAmount: row.total_amount ?? null,
    notes: row.notes ?? "",
    documentPaths: safeJson(row.document_paths, []),
    metadata: safeJson(row.metadata, { employeeRows: [] }),
    isAutoGenerated: row.is_auto_generated === 1,
    createdAt: row.created_at, updatedAt: row.updated_at,
    submittedAt: row.submitted_at ?? null,
  };
}

function safeJson(raw, fallback) {
  if (!raw) return fallback;
  try { return JSON.parse(raw); } catch { return fallback; }
}

function nowIso() {
  return new Date().toISOString();
}

function genId(prefix) {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
}

function hashPassword(plain) {
  return crypto.createHash("sha256").update(plain).digest("hex");
}

function verifyPassword(plain, hash) {
  return hashPassword(plain) === hash;
}

module.exports = { ok, created, fail, paged, formatTask, formatEmployee, formatEntry, safeJson, nowIso, genId, hashPassword, verifyPassword };
