/**
 * Shared response helpers — consistent envelope for all endpoints.
 */

export function ok(data: unknown, message = "Success", extra?: object) {
  return { success: true, message, data, ...extra };
}

export function created(data: unknown, message = "Created") {
  return { success: true, message, data };
}

export function fail(message: string, errors?: { field: string; message: string }[]) {
  return { success: false, message, ...(errors ? { errors } : {}) };
}

export function paged(
  data: unknown[],
  message: string,
  page: number,
  per_page: number,
  total_items: number,
) {
  return {
    success: true,
    message,
    data,
    pagination: {
      page,
      per_page,
      total_items,
      total_pages: Math.ceil(total_items / per_page),
    },
  };
}

/** Build camelCase task object from DB row */
export function formatTask(row: Record<string, unknown>) {
  return {
    id: row.id,
    clientId: row.client_id,
    assignedBy: row.assigned_by,
    title: row.title,
    description: row.description,
    status: row.status,
    adminStatus: row.admin_status,
    taskType: row.task_type,
    metadata: safeJson(row.metadata as string, {}),
    completionNote: row.completion_note ?? null,
    completedAt: row.completed_at ?? null,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

export function formatEmployee(row: Record<string, unknown>) {
  return {
    id: row.id,
    name: row.name,
    email: row.email ?? null,
    firstName: row.first_name ?? null,
    lastName: row.last_name ?? null,
    middleName: row.middle_name ?? null,
    dateOfBirth: row.date_of_birth ?? null,
    gender: row.gender ?? null,
    phone: row.phone ?? null,
    sin: row.sin ?? null,
    addressLine1: row.address_line_1 ?? null,
    addressLine2: row.address_line_2 ?? null,
    city: row.city ?? null,
    country: row.country ?? null,
    provinceState: row.province_state ?? null,
    postalCode: row.postal_code ?? null,
    startDate: row.start_date ?? null,
    position: row.position ?? null,
    department: row.department ?? null,
    hourlyRate: row.hourly_rate ?? null,
    federalTaxCredit: row.federal_tax_credit ?? null,
    provincialTaxCredit: row.provincial_tax_credit ?? null,
    salary: row.salary ?? null,
    metadata: safeJson(row.metadata as string, {}),
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

export function formatEntry(row: Record<string, unknown>) {
  return {
    id: row.id,
    periodLabel: row.period_label,
    periodStart: row.period_start,
    periodEnd: row.period_end,
    status: row.status,
    employeeIds: safeJson(row.employee_ids as string, []),
    totalAmount: row.total_amount ?? null,
    notes: row.notes ?? "",
    documentPaths: safeJson(row.document_paths as string, []),
    metadata: safeJson(row.metadata as string, { employeeRows: [] }),
    isAutoGenerated: row.is_auto_generated === 1,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    submittedAt: row.submitted_at ?? null,
  };
}

export function safeJson<T>(raw: string | null | undefined, fallback: T): T {
  if (!raw) return fallback;
  try {
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}

export function nowIso() {
  return new Date().toISOString();
}

export function genId(prefix: string) {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
}

/** Simple password hash (SHA-256 via Web Crypto, for testing only) */
export async function hashPassword(plain: string): Promise<string> {
  const enc = new TextEncoder().encode(plain);
  const buf = await crypto.subtle.digest("SHA-256", enc);
  return Array.from(new Uint8Array(buf))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

export async function verifyPassword(plain: string, hash: string): Promise<boolean> {
  return (await hashPassword(plain)) === hash;
}
