/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as TimeRouteImport } from './routes/time'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SubmissionHistoryRouteImport } from './routes/submission-history'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OcrRouteImport } from './routes/ocr'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SalesIndexRouteImport } from './routes/sales/index'
import { Route as CostsIndexRouteImport } from './routes/costs/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as BankIndexRouteImport } from './routes/bank/index'
import { Route as SettingsVaultRouteImport } from './routes/settings/vault'
import { Route as SettingsSubscriptionRouteImport } from './routes/settings/subscription'
import { Route as SettingsMileageRouteImport } from './routes/settings/mileage'
import { Route as SettingsListsRouteImport } from './routes/settings/lists'
import { Route as SettingsExtractionRouteImport } from './routes/settings/extraction'
import { Route as SettingsExportsRouteImport } from './routes/settings/exports'
import { Route as SettingsConnectionsRouteImport } from './routes/settings/connections'
import { Route as SettingsBusinessProfileRouteImport } from './routes/settings/business-profile'
import { Route as SettingsAutomationRouteImport } from './routes/settings/automation'
import { Route as SettingsApprovalsRouteImport } from './routes/settings/approvals'
import { Route as ClientsClientIdRouteImport } from './routes/clients/$clientId'
import { Route as ClientsClientIdIndexRouteImport } from './routes/clients/$clientId.index'
import { Route as ClientsClientIdTabRouteImport } from './routes/clients/$clientId.$tab'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeRoute = TimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionHistoryRoute = SubmissionHistoryRouteImport.update({
  id: '/submission-history',
  path: '/submission-history',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrRoute = OcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsIndexRoute = CostsIndexRouteImport.update({
  id: '/costs/',
  path: '/costs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankIndexRoute = BankIndexRouteImport.update({
  id: '/bank/',
  path: '/bank/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsVaultRoute = SettingsVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSubscriptionRoute = SettingsSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMileageRoute = SettingsMileageRouteImport.update({
  id: '/mileage',
  path: '/mileage',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsListsRoute = SettingsListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExtractionRoute = SettingsExtractionRouteImport.update({
  id: '/extraction',
  path: '/extraction',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExportsRoute = SettingsExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBusinessProfileRoute = SettingsBusinessProfileRouteImport.update({
  id: '/business-profile',
  path: '/business-profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAutomationRoute = SettingsAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApprovalsRoute = SettingsApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => SettingsRoute,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdIndexRoute = ClientsClientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsClientIdRoute,
} as any)
const ClientsClientIdTabRoute = ClientsClientIdTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => ClientsClientIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/ocr': typeof OcrRoute
  '/settings': typeof SettingsRouteWithChildren
  '/submission-history': typeof SubmissionHistoryRoute
  '/tasks': typeof TasksRoute
  '/templates': typeof TemplatesRoute
  '/time': typeof TimeRoute
  '/workflows': typeof WorkflowsRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/settings/approvals': typeof SettingsApprovalsRoute
  '/settings/automation': typeof SettingsAutomationRoute
  '/settings/business-profile': typeof SettingsBusinessProfileRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/exports': typeof SettingsExportsRoute
  '/settings/extraction': typeof SettingsExtractionRoute
  '/settings/lists': typeof SettingsListsRoute
  '/settings/mileage': typeof SettingsMileageRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/settings/vault': typeof SettingsVaultRoute
  '/bank/': typeof BankIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/costs/': typeof CostsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/clients/$clientId/$tab': typeof ClientsClientIdTabRoute
  '/clients/$clientId/': typeof ClientsClientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/ocr': typeof OcrRoute
  '/submission-history': typeof SubmissionHistoryRoute
  '/tasks': typeof TasksRoute
  '/templates': typeof TemplatesRoute
  '/time': typeof TimeRoute
  '/workflows': typeof WorkflowsRoute
  '/settings/approvals': typeof SettingsApprovalsRoute
  '/settings/automation': typeof SettingsAutomationRoute
  '/settings/business-profile': typeof SettingsBusinessProfileRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/exports': typeof SettingsExportsRoute
  '/settings/extraction': typeof SettingsExtractionRoute
  '/settings/lists': typeof SettingsListsRoute
  '/settings/mileage': typeof SettingsMileageRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/settings/vault': typeof SettingsVaultRoute
  '/bank': typeof BankIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/costs': typeof CostsIndexRoute
  '/sales': typeof SalesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/clients/$clientId/$tab': typeof ClientsClientIdTabRoute
  '/clients/$clientId': typeof ClientsClientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/ocr': typeof OcrRoute
  '/settings': typeof SettingsRouteWithChildren
  '/submission-history': typeof SubmissionHistoryRoute
  '/tasks': typeof TasksRoute
  '/templates': typeof TemplatesRoute
  '/time': typeof TimeRoute
  '/workflows': typeof WorkflowsRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/settings/approvals': typeof SettingsApprovalsRoute
  '/settings/automation': typeof SettingsAutomationRoute
  '/settings/business-profile': typeof SettingsBusinessProfileRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/exports': typeof SettingsExportsRoute
  '/settings/extraction': typeof SettingsExtractionRoute
  '/settings/lists': typeof SettingsListsRoute
  '/settings/mileage': typeof SettingsMileageRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/settings/vault': typeof SettingsVaultRoute
  '/bank/': typeof BankIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/costs/': typeof CostsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/clients/$clientId/$tab': typeof ClientsClientIdTabRoute
  '/clients/$clientId/': typeof ClientsClientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/files'
    | '/inbox'
    | '/insights'
    | '/ocr'
    | '/settings'
    | '/submission-history'
    | '/tasks'
    | '/templates'
    | '/time'
    | '/workflows'
    | '/clients/$clientId'
    | '/settings/approvals'
    | '/settings/automation'
    | '/settings/business-profile'
    | '/settings/connections'
    | '/settings/exports'
    | '/settings/extraction'
    | '/settings/lists'
    | '/settings/mileage'
    | '/settings/subscription'
    | '/settings/vault'
    | '/bank/'
    | '/clients/'
    | '/costs/'
    | '/sales/'
    | '/settings/'
    | '/clients/$clientId/$tab'
    | '/clients/$clientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/files'
    | '/inbox'
    | '/insights'
    | '/ocr'
    | '/submission-history'
    | '/tasks'
    | '/templates'
    | '/time'
    | '/workflows'
    | '/settings/approvals'
    | '/settings/automation'
    | '/settings/business-profile'
    | '/settings/connections'
    | '/settings/exports'
    | '/settings/extraction'
    | '/settings/lists'
    | '/settings/mileage'
    | '/settings/subscription'
    | '/settings/vault'
    | '/bank'
    | '/clients'
    | '/costs'
    | '/sales'
    | '/settings'
    | '/clients/$clientId/$tab'
    | '/clients/$clientId'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/dashboard'
    | '/files'
    | '/inbox'
    | '/insights'
    | '/ocr'
    | '/settings'
    | '/submission-history'
    | '/tasks'
    | '/templates'
    | '/time'
    | '/workflows'
    | '/clients/$clientId'
    | '/settings/approvals'
    | '/settings/automation'
    | '/settings/business-profile'
    | '/settings/connections'
    | '/settings/exports'
    | '/settings/extraction'
    | '/settings/lists'
    | '/settings/mileage'
    | '/settings/subscription'
    | '/settings/vault'
    | '/bank/'
    | '/clients/'
    | '/costs/'
    | '/sales/'
    | '/settings/'
    | '/clients/$clientId/$tab'
    | '/clients/$clientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  FilesRoute: typeof FilesRoute
  InboxRoute: typeof InboxRoute
  InsightsRoute: typeof InsightsRoute
  OcrRoute: typeof OcrRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SubmissionHistoryRoute: typeof SubmissionHistoryRoute
  TasksRoute: typeof TasksRoute
  TemplatesRoute: typeof TemplatesRoute
  TimeRoute: typeof TimeRoute
  WorkflowsRoute: typeof WorkflowsRoute
  ClientsClientIdRoute: typeof ClientsClientIdRouteWithChildren
  BankIndexRoute: typeof BankIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  CostsIndexRoute: typeof CostsIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time': {
      id: '/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof TimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submission-history': {
      id: '/submission-history'
      path: '/submission-history'
      fullPath: '/submission-history'
      preLoaderRoute: typeof SubmissionHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr': {
      id: '/ocr'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof OcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs/': {
      id: '/costs/'
      path: '/costs'
      fullPath: '/costs/'
      preLoaderRoute: typeof CostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/': {
      id: '/bank/'
      path: '/bank'
      fullPath: '/bank/'
      preLoaderRoute: typeof BankIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/vault': {
      id: '/settings/vault'
      path: '/vault'
      fullPath: '/settings/vault'
      preLoaderRoute: typeof SettingsVaultRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/subscription': {
      id: '/settings/subscription'
      path: '/subscription'
      fullPath: '/settings/subscription'
      preLoaderRoute: typeof SettingsSubscriptionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mileage': {
      id: '/settings/mileage'
      path: '/mileage'
      fullPath: '/settings/mileage'
      preLoaderRoute: typeof SettingsMileageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/lists': {
      id: '/settings/lists'
      path: '/lists'
      fullPath: '/settings/lists'
      preLoaderRoute: typeof SettingsListsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/extraction': {
      id: '/settings/extraction'
      path: '/extraction'
      fullPath: '/settings/extraction'
      preLoaderRoute: typeof SettingsExtractionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/exports': {
      id: '/settings/exports'
      path: '/exports'
      fullPath: '/settings/exports'
      preLoaderRoute: typeof SettingsExportsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/business-profile': {
      id: '/settings/business-profile'
      path: '/business-profile'
      fullPath: '/settings/business-profile'
      preLoaderRoute: typeof SettingsBusinessProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/automation': {
      id: '/settings/automation'
      path: '/automation'
      fullPath: '/settings/automation'
      preLoaderRoute: typeof SettingsAutomationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/approvals': {
      id: '/settings/approvals'
      path: '/approvals'
      fullPath: '/settings/approvals'
      preLoaderRoute: typeof SettingsApprovalsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId/': {
      id: '/clients/$clientId/'
      path: '/'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof ClientsClientIdIndexRouteImport
      parentRoute: typeof ClientsClientIdRoute
    }
    '/clients/$clientId/$tab': {
      id: '/clients/$clientId/$tab'
      path: '/$tab'
      fullPath: '/clients/$clientId/$tab'
      preLoaderRoute: typeof ClientsClientIdTabRouteImport
      parentRoute: typeof ClientsClientIdRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsApprovalsRoute: typeof SettingsApprovalsRoute
  SettingsAutomationRoute: typeof SettingsAutomationRoute
  SettingsBusinessProfileRoute: typeof SettingsBusinessProfileRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsExportsRoute: typeof SettingsExportsRoute
  SettingsExtractionRoute: typeof SettingsExtractionRoute
  SettingsListsRoute: typeof SettingsListsRoute
  SettingsMileageRoute: typeof SettingsMileageRoute
  SettingsSubscriptionRoute: typeof SettingsSubscriptionRoute
  SettingsVaultRoute: typeof SettingsVaultRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsApprovalsRoute: SettingsApprovalsRoute,
  SettingsAutomationRoute: SettingsAutomationRoute,
  SettingsBusinessProfileRoute: SettingsBusinessProfileRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsExportsRoute: SettingsExportsRoute,
  SettingsExtractionRoute: SettingsExtractionRoute,
  SettingsListsRoute: SettingsListsRoute,
  SettingsMileageRoute: SettingsMileageRoute,
  SettingsSubscriptionRoute: SettingsSubscriptionRoute,
  SettingsVaultRoute: SettingsVaultRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ClientsClientIdRouteChildren {
  ClientsClientIdTabRoute: typeof ClientsClientIdTabRoute
  ClientsClientIdIndexRoute: typeof ClientsClientIdIndexRoute
}

const ClientsClientIdRouteChildren: ClientsClientIdRouteChildren = {
  ClientsClientIdTabRoute: ClientsClientIdTabRoute,
  ClientsClientIdIndexRoute: ClientsClientIdIndexRoute,
}

const ClientsClientIdRouteWithChildren = ClientsClientIdRoute._addFileChildren(
  ClientsClientIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  FilesRoute: FilesRoute,
  InboxRoute: InboxRoute,
  InsightsRoute: InsightsRoute,
  OcrRoute: OcrRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SubmissionHistoryRoute: SubmissionHistoryRoute,
  TasksRoute: TasksRoute,
  TemplatesRoute: TemplatesRoute,
  TimeRoute: TimeRoute,
  WorkflowsRoute: WorkflowsRoute,
  ClientsClientIdRoute: ClientsClientIdRouteWithChildren,
  BankIndexRoute: BankIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  CostsIndexRoute: CostsIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
